// svelte/src/components/NewsList.svelte
<script>
  import { onMount, tick } from "svelte";
  import { api } from "../api";
  import { getNewsData } from "../dto";
  import NewsItem from "./NewsItem.svelte";
  import NewsListMeta from "./NewsListMeta.svelte";

  $: input = "ukraine";
  $: error = "";
  $: data = [];
  $: loading = false;
  $: meta = {
    page: 1,
    pageSize: 20,
    totalResults: 0,
  };
  $: searchTimeout = undefined;

  const onChange = (e) => {
    console.log(e.target.value);

    if (searchTimeout) {
      clearTimeout(searchTimeout)
    }
    input = e.target.value;
    if (e.target.value.length > 3) {
      searchTimeout = setTimeout(fetchData, 1000);
    }
  };

  const fetchData = async () => {
    if (loading) return;
    loading = true;
    const response = await api.getEverething({
      q: input,
      page: meta.page,
      pageSize: meta.pageSize,
    });
    if (response.error) {
      error = response.error;
      data = [];
    } else if (response.data) {
      data = response.data.articles.map(getNewsData);
      meta.totalResults = response.data.totalResults;
    }
    loading = false;
  };

  const setPage = (page) => {
    meta = {
      ...meta,
      page,
    };
    fetchData();
  };

  onMount(fetchData);
</script>

<div class="container-flex-col full-width">
  <h2>Поиск новостей</h2>
  <input class="main-input" on:input={onChange} value={input} />

  <NewsListMeta {meta} {setPage} />

  {#if loading}
    <h5>Loading...</h5>
  {/if}

  {#key data}
    <div class="news-list">
      {#each data as item}
        <NewsItem {...item} />
      {/each}
    </div>
  {/key}

  <NewsListMeta {meta} {setPage} />
</div>

<style>
  .news-list {
    display: grid;
    grid-template-columns: repeat(auto-fit, 320px);
    gap: 20px;
    align-items: flex-start;
    justify-content: center;
    flex-wrap: wrap;
  }

  .main-input {
    max-width: 80vw;
    margin: 20px auto;
    width: 100%;
  }
</style>

// stencil/src/components/newsList/news-list.tsx
import { Component, h, State, Method, Watch, getAssetPath } from '@stencil/core';
import { api } from '../../api';
import { getNewsItemData } from '../../dto/NewsItem';
import { Meta, NewsItemData } from '../../types';
import { NewsListItem } from './news-list-item';
import { NewsListMeta } from './news-list-meta';

@Component({
  tag: 'news-list',
  styleUrl: 'news-list.css',
})
export class NewsList {
  @State() input: string = 'ukraine';
  @State() error: string = '';
  @State() data: NewsItemData[] = [];
  @State() loading: boolean = false;
  @State() meta: Meta = {
    page: 1,
    pageSize: 20,
    totalResults: 0,
  };
  @State() timer: ReturnType<typeof setTimeout> | null = null;

  componentWillLoad() {
    console.log('load');
    this.fetchData();
  }

  clearTimer = () => {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  };

  @Method()
  async fetchData() {
    if (this.loading) return;
    this.loading = true;
    const response = await api.getEverething({
      q: this.input,
      page: this.meta.page,
      pageSize: this.meta.pageSize,
    });

    if (response.error) {
      this.error = response.error;
    } else if (response.data) {
      this.data = response.data.articles.map(getNewsItemData);
      this.meta = {
        ...this.meta,
        totalResults: response.data.totalResults,
      };
    }
    this.loading = false;
    this.clearTimer();
  }

  setPage = (page: number) => {
    console.log(page)
    this.meta = {
      ...this.meta,
      page,
    };
    setTimeout(this.fetchData.bind(this));
  };

  changeInput(e: any) {
    this.input = e.target.value;
    if (this.timer) {
      this.clearTimer();
    }
    this.timer = setTimeout(this.fetchData.bind(this), 1000);
  }

  render() {
    return (
      <div class="container-flex-col full-width">
        <h2>Поиск новостей</h2>
        <input class="main-input" value={this.input} onInput={this.changeInput.bind(this)} />
        <NewsListMeta meta={this.meta} setPage={this.setPage} />

        <div class="news-list">
          {this.data.map(el => (
            <NewsListItem data={el} defaultImg={getAssetPath("/assets/icon/icon.png")}/>
          ))}
        </div>

        <NewsListMeta meta={this.meta} setPage={this.setPage} />
      </div>
    );
  }
}
