// astro/src/components/NewsListMeta.tsx
import { getSearchMeta } from "../helpers/getSearchMeta";
import type { Meta } from "../types";
import cls from "classnames";
import { useState } from "react";

interface Props {
  meta: Meta;
  setPage: (v: number) => void;
}

export default function NewsListMeta(props: Props) {
  const [numbers, setNumbers] = useState(getSearchMeta(props.meta));

  return (
    <div className="meta">
      {numbers.map((item) => (
        <span
          key={item}
          className={cls({
            "item": true,
            "selected": item === props.meta.page,
          })}
          onMouseDown={() => (item ? props.setPage(item) : undefined)}
        >
          {item}
        </span>
      ))}
    </div>
  );
}

// solidjs/src/components/NewsListMeta.tsx
import { For } from "solid-js";
import { getSearchMeta } from "../helpers/getSearchMeta";
import { Meta } from "../types";
import styles from './NewsList.module.css';
import cls from 'classnames';

interface Props {
  meta: Meta
  setPage: (v: number) => void
}

export default function NewsListMeta (props: Props) {

  const { meta, setPage } = props;

  const numbers = getSearchMeta(meta);

  return (
    <div class={styles.meta}>
      <For each={numbers} fallback={"Loading"}>
        {(item) => (
          <span class={cls({
            [styles.item] : true,
            [styles.selected] : item === meta.page
          })} onMouseDown={() => item ? setPage(item) : undefined}>
            {item}
          </span>
        )}
      </For>
    </div>    
  )

}
