// svelte/src/components/NewsItem.svelte
<script>

  const { 
    author, 
    description, 
    title, 
    url, 
    urlToImage = "url(/favicon.png)",
    // publishedAt, 
    // source, 
    // content, 
   } = $$props;

   console.log(urlToImage);

   const onImageError = e => {
    console.log('error')
    console.log(e)
   }

</script>

<div class="news-item">
  <a class="news-item__link full-width" href={url} target="_blank"/>
  <img src={urlToImage || `/favicon.png`} alt="image" class="__image" on:error={onImageError} />
  <h5>{title}</h5>
  <p>{description}</p>
  <h6>{author}</h6>
</div>

<style>
  .news-item {
    padding: 15px;
    height: -webkit-fill-available;
    max-width: 320px;
    border: 1px solid black;
    display: flex;
    flex-direction: column;
    align-items: center;
    position: relative;
  }

  .news-item h6 {
    color: aquamarine;
  }

  .news-item p {
    text-align: left;
  }

  .news-item__link {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    opacity: 0;
    z-index: 5;
    cursor: pointer;
  }

  .news-item .__image {
    width: 100%;
    height: auto;
    max-height: 162px;
  }
</style>

// astro/src/components/NewsItem.tsx
import cls from "classnames";
import defaultImg from '../assets/favicon.ico'
import type { NewsItemData } from "../types";

interface Props {
  data: NewsItemData;
}

export default function NewsItem(props: Props) {
  const { data } = props;

  return (
    <div className="news-list-item">
      {data.url && <a
          className={cls(["news-list-item-link", "full-width"])}
          href={data.url as string}
          target="_blank"
        />}
      <img
        src={data.urlToImage || defaultImg}
        alt="image"
        className="news-list-item-image"
      />
      <h5>{data.title}</h5>
      <p>{data.description}</p>
      <h6>{data.author}</h6>
    </div>
  );
}
