// svelte/src/components/NewsListMeta.svelte
<script>
  import { getSearchMeta } from "../helpers/getSearchMeta";
  import { afterUpdate, beforeUpdate } from "svelte";
  const { setPage } = $$props;

  $: numbers = getSearchMeta($$props.meta);

  beforeUpdate(() => {
    numbers = getSearchMeta($$props.meta);
  });

  afterUpdate(() => {
    console.log($$props.meta);
  })

</script>

<div class="news-list-meta">
  {#each numbers as number}
      <span
        on:mousedown={() => setPage(number)}
        class:item={true}
        class:selected={number === $$props.meta.page}>{number || "..."}</span
      >
  {/each}
</div>

<style>
  .news-list-meta {
    margin: 20px 0;
  }

  .item {
    margin: 10px;
    cursor: pointer;
  }

  .selected {
    color: red;
  }
</style>

// qwik-app/src/components/news-list/news-list-meta.tsx
import { $, component$ } from "@builder.io/qwik";
import { getSearchMeta } from "~/helpers/getSearchMeta";
import { Meta } from "~/types";

interface NewsListMetaProps {
  meta: Meta;
  setPage: (page: number) => void;
}

export default component$(({ meta, setPage } : NewsListMetaProps) => {

  const numbers = getSearchMeta(meta);

  const onClick = $((v: number| null) => {
    if (v) {
      setPage(v)
    }
  })


  return (
    <div class="meta">
      {numbers.map(el => (
        <span 
          key={el}
          onClick$={() => onClick(el)} 
          class={el === meta.page ? 'news-list-meta-item news-list-meta-item-selected' : 'news-list-meta-item'}
          >
          {el || '...'}
        </span>
      ))}
    </div>
  )

})
